import type { NextComponentType, NextPageContext } from 'next';
import Navbar from './Navbar';
import { ReactElement } from 'react';
import Head from 'next/head';
import { Roboto } from '@next/font/google';

const roboto = Roboto({ weight: '400', subsets: ['latin'] });

interface Props {
    children: ReactElement;
}

const Layout: NextComponentType<NextPageContext, {}, Props> = ({ children }) => {
    return (
        <>
            <Head>
                <title>Nathan Photography</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/logo.png" />
            </Head>
            <div
                className="w-full h-screen bg-cover bg-fixed bg-center text-xl"
                style={{ backgroundImage: "url('/background.jpg')" }}
            >
                <div className="w-full h-screen bg-black/50">
                    <Navbar />
                    <main className={`${roboto.className} px-4 py-2`}>{children}</main>
                </div>
            </div>
        </>
    );
};

export default Layout;
