import { Roboto } from '@next/font/google'
import type { NextComponentType, NextPageContext } from 'next'
import Head from 'next/head'
import { ReactElement } from 'react'
import Navbar from './Navbar'

const roboto = Roboto({ weight: '400', subsets: ['latin'] })

interface Props {
    children: ReactElement
}

const Layout: NextComponentType<NextPageContext, {}, Props> = ({
    children,
}) => {
    return (
        <>
            <Head>
                <title>Nathan Photography</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/logo.png" />
            </Head>
            <div
                id="layout"
                className="w-full overflow-auto bg-cover bg-fixed bg-center lg:text-xl"
            >
                <div className="flex min-h-screen w-full flex-col bg-black/50">
                    <Navbar />
                    <main
                        className={`${roboto.className} flex flex-1 items-center justify-center px-4 py-2`}
                    >
                        <div className="container text-gray-200">
                            {children}
                        </div>
                    </main>
                </div>
            </div>
        </>
    )
}

export default Layout
